from reverse import reverse_s


def test_reverse_word():
    assert reverse_s(["h", "e", "l", "l", "o"]) == ["o", "l", "l", "e", "h"]
    assert reverse_s(
        [
            "A",
            " ",
            "m",
            "a",
            "n",
            ",",
            " ",
            "a",
            " ",
            "p",
            "l",
            "a",
            "n",
            ",",
            " ",
            "a",
            " ",
            "c",
            "a",
            "n",
            "a",
            "l",
            ":",
            " ",
            "P",
            "a",
            "n",
            "a",
            "m",
            "a",
        ]
    ) == [
        "a",
        "m",
        "a",
        "n",
        "a",
        "P",
        " ",
        ":",
        "l",
        "a",
        "n",
        "a",
        "c",
        " ",
        "a",
        " ",
        ",",
        "n",
        "a",
        "l",
        "p",
        " ",
        "a",
        " ",
        ",",
        "n",
        "a",
        "m",
        " ",
        "A",
    ]
